=== khaimed/ENSET-YOUSSFI-Practical_Activity-XML-and-Web_Services/rapport/rapport.dtd
<!ELEMENT rapport (mondat+)>
<!ELEMENT mondat (expediteur, destinataire) >
<!ELEMENT expediteur EMPTY>
<!ELEMENT destinataire EMPTY>

<!ATTLIST mondat 
    num NMTOKEN #REQUIRED
    date CDATA #REQUIRED
    montant CDATA #REQUIRED
    etat (Reçu| Non_Reçu) 'Non_Reçu'
>
<!ATTLIST expediteur
    cin CDATA #REQUIRED
    nom CDATA #REQUIRED
    prenom CDATA #REQUIRED
    ville CDATA #REQUIRED
>
<!ATTLIST destinataire
    cin CDATA #REQUIRED
    nom CDATA #REQUIRED
    prenom CDATA #REQUIRED
    ville CDATA #REQUIRED
>

=== khaimed/ENSET-YOUSSFI-Practical_Activity-XML-and-Web_Services/rapport/rapport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rapport SYSTEM "rapport.dtd">
<rapport>
    <mondat num="11" date="2023-11-01" montant="2300" etat="Reçu">
        <expediteur cin="DS12312" nom="a" prenom="b" ville="casa"/>
        <destinataire cin="QA123214" nom="c" prenom="d" ville="fes"/>
    </mondat>
    <mondat num="14" date="2023-12-11" montant="1200" etat="Non_Reçu">
        <expediteur cin="AQ12312" nom="a" prenom="b" ville="casa"/>
        <destinataire cin="FD123214" nom="c" prenom="d" ville="fes"/>
    </mondat>
    <mondat num="11" date="2023-01-13" montant="1200" etat="Reçu">
        <expediteur cin="GF12312" nom="a" prenom="b" ville="casa"/>
        <destinataire cin="SE123214" nom="c" prenom="d" ville="fes"/>
    </mondat>
</rapport>
