=== khaimed/ENSET-YOUSSFI-Practical_Activity-XML-and-Web_Services/rapport2/rapport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="rapport">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="mondat" minOccurs="1" maxOccurs="unbounded" type="mondat_type"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="mondat_type">
        <xsd:sequence>
            <xsd:element name="expediteur" type="exp_dest_type"></xsd:element>
            <xsd:element name="destinataire" type="exp_dest_type"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="num" type="xsd:int" use="required"></xsd:attribute>
        <xsd:attribute name="date" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="montant" type="xsd:double" use="required"></xsd:attribute>
        <xsd:attribute name="etat" default="non reçu">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="reçu"></xsd:enumeration>
                    <xsd:enumeration value="non reçu"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="exp_dest_type">
        <xsd:attribute name="cin" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="nom" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="prenom" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="ville" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== khaimed/ENSET-YOUSSFI-Practical_Activity-XML-and-Web_Services/rapport2/rapport.xml
<?xml version="1.0" encoding="UTF-8"?>
<rapport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/hp/Documents/XML/rapport.xsd">
    <mondat num="12" date="2023-12-21" montant="340.20" etat="reçu">
        <expediteur cin="DS12345" nom="a" prenom="b"/>
        <destinataire cin="QA54666" nom="x" prenom="c"/>
    </mondat>
    <mondat num="12" date="2023-12-21" montant="340.20" etat="reçu">
        <expediteur cin="DS12345" nom="a" prenom="b"/>
        <destinataire cin="QA54666" nom="x" prenom="c"/>
    </mondat>
    <mondat num="12" date="2023-01-21" montant="340.20" etat="reçu">
        <expediteur cin="DS43245" nom="g" prenom="j"/>
        <destinataire cin="QA55646" nom="z" prenom="g"/>
    </mondat>
</rapport>
